FROM pearlthoughts/smw:latest
WORKDIR /srv/smw
RUN apt install git supervisor -y
RUN chmod -R 777 /srv/smw/
COPY ./composer* /srv/smw/
RUN composer install
RUN mv vendor/bower-asset vendor/bower
COPY ./docker/supervisor/queue.conf /etc/supervisor/conf.d/queue.conf

COPY ./docker/php/permissions.sh /
RUN sed -i -e 's/\r$//' /permissions.sh
RUN chmod +x /permissions.sh