version: "3.7"
services:
  smw:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-dev
    image: smw-image
    container_name: smw-app
    ports: 
      - 8080:80
    volumes:
      - ./:/srv/smw
      - ./.env:/srv/smw/.env
      - ./docker/php/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - /srv/smw/vendor
      - /srv/smw/frontend/web/assets/
      - /srv/smw/backend/web/assets/
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    restart: always
    container_name: smw-db
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}


volumes:
  mysql: