name: Deploy to dev
on:
    push:
        branches: [develop]

jobs:
    dev-env:
        runs-on: ubuntu-latest

        steps:
            - name: Deploying in "SMW_DEV"
              uses: appleboy/ssh-action@master
              with:
                  host: 3.98.69.25
                  username: ubuntu
                  key: ${{ secrets.KEY_VALUE }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  port: 22
                  script: |                 
                    cd /srv/smw
                    pwd
                    git pull origin develop 
                    composer install
                    php console/yii migrate --interactive=0
                    exit 
